title = "My New Hugo Site"
baseURL = "https://curttimson.github.io/nixxi-timson/"
languageCode = "en-us"
theme = "forty"

[params]
    title = "Nicola Timson"
    major = "Nicola Timson"
    coverimageurl = "images/cover.jpg"
    subtitle = "Lorem Ipsum"
    subtitleline2 = "2nd line"
    bannerCTA = "View Portfolio"

    [params.author]
      firstname = "Nicola"
      lastname = "Timson"

    [params.social]
      twitter = "https://twitter.com/_nixxi"
      # facebook = "facebook"
      # instagram = "instagram"
      # github = "github"
      linkedin = "https://www.linkedin.com/in/nicola-timson-463506128/"
