languageCode = "en-us"
title = "Nicola Timson"
baseURL = "https://nicolatimson.co.uk/"
theme = "massively"

[params.posts]
    foldername = "post"
    pagesize = "6"
    featuredpost = "false"

[params.settings]
    googleanalytics = "UA-107434352-1"
    disqus = "hugo-massively"